import {StyleSheet} from 'react-native';

export const style = StyleSheet.create({
  container: {flex: 1, marginTop: 20},
  containerSearch: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textInput: {
    width: '90%',
    height: 40,
    borderWidth: 1,
    borderRadius: 20,
    borderColor: 'red',
    paddingLeft: 20,
  },
  containerIconSearch: {
    position: 'absolute',
    right: 30,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderLeftWidth: 1,
    borderColor: 'red',
  },
  containerSwiper: {height: 200},
  swiper: {backgroundColor: 'red', marginTop: 10},
  imageSwiper: {width: '100%', height: 200},
  containerListItemLabel: {marginTop: 40, marginHorizontal: 20},
  textLabel: {fontSize: 26, color: 'orange', fontWeight: '500'},
  containerList: {
    marginTop: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  btnItem: {width: '48%', marginTop: 10},
  containerDiscount: {
    position: 'absolute',
    backgroundColor: 'red',
    height: 30,
    width: 80,
    bottom: 85,
    zIndex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textDiscount: {color: 'white', fontSize: 14, fontWeight: '500'},
  containerInfor: {marginTop: 5},
  textName: {fontSize: 16, fontWeight: '500', color: 'black'},
  textPriceDiscount: {fontSize: 16, fontWeight: '500', color: 'black'},
  textPrice: {fontSize: 16, fontWeight: '500', color: 'red'},
  listImageItem: {width: '100%', height: 130, borderRadius: 10},
});
