import { StyleSheet } from "react-native";

export const style = StyleSheet.create({
  container: {flex: 1},
  containerHeader: {
    backgroundColor: '#fc5653',
    height: 50,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  textHeader: {fontSize: 26, fontWeight: '500', color: 'white'},
  containerCart: {
    flex: 1,
  },
  innerContainerCart: {
    height: 100,
    margin: 10,
    flexDirection: 'row',
  },
  containerImageItem: {width: '35%'},
  imageItem: {width: '100%', height: '100%', borderRadius: 10},
  containerInforItem: {
    width: '45%',
    paddingLeft: 10,
    rowGap: 10,
  },
  textName: {fontSize: 18, fontWeight: '500', color: 'black'},
  textPrice: {fontSize: 18, fontWeight: '500', color: 'black'},
  containerUpDownQuality: {flexDirection: 'row', gap: 10},
  btnUpDownQuality: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
  },
  textUpAndDownQuality: {fontSize: 18, color: 'black', fontWeight: '500'},
  containerRemoveItem: {
    width: '20%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnRemove: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 70,
    height: 45,
    backgroundColor: 'red',
    borderRadius: 8,
  },
  textRemove: {fontSize: 18, fontWeight: '500', color: 'white'},
  line: {
    borderWidth: 1,
    height: 1,
    marginTop: 5,
    marginBottom: 10,
    borderColor: 'black',
  },
  containerOrderAndTotalPrice: {
    flexDirection: 'row',
    width: '100%',
    height: 70,
    padding: 10,
  },
  containerTotalPrice: {
    width: '65%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  textTotal: {fontSize: 20, fontWeight: '700', color: 'black'},
  textPrice: {fontSize: 20, color: 'red', marginLeft: 10},
  containerOrder: {
    width: '35%',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  btnOrder: {
    backgroundColor: 'green',
    width: 100,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  textOrder: {fontSize: 18, fontWeight: '500', color: 'white'},
  containerButton: {
    height: '10%',
    flexDirection: 'row',
    marginTop: 30,
    justifyContent: 'space-between',
  },
  btnCancelModal: {
    width: '47%',
    backgroundColor: '#bdbdbd',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  btnAddToCartModal: {
    width: '47%',
    backgroundColor: 'green',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  textButton: {fontSize: 16, fontWeight: '500', color: 'white'},
  containerModal: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  containerFormOrderModal: {
    width: '100%',
    height: '80%',
    backgroundColor: 'white',
    padding: 20,
  },
  containerHeaderModal: {flexDirection: 'row', justifyContent: 'space-between'},
  textHeaderModal: {fontSize: 18, fontWeight: '500', color: 'black'},
  textPriceModal: {fontSize: 18, fontWeight: '500', color: 'red'},
  textInforModal: {
    fontSize: 16,
    fontWeight: '500',
    color: 'black',
    marginTop: 10,
  },
  containerFormInputModal: {gap: 8, marginTop: 10},
  textLabelInputModal: {
    fontSize: 16,
    fontWeight: '500',
  },
  inputModal: {
    width: '100%',
    borderWidth: 1,
    borderRadius: 10,
    paddingLeft: 10,
  },
});