import {StyleSheet} from 'react-native';

export const style = StyleSheet.create({
  container: {flex: 1},
  containerHeader: {
    backgroundColor: '#fc5653',
    height: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  textHeader: {fontSize: 26, fontWeight: '500', color: 'white'},
  imageItem: {height: 200},
  containerInforItem: {marginHorizontal: 20, marginTop: 10},
  textName: {fontSize: 20, fontWeight: '500', color: 'black'},
  textPrice: {fontSize: 20, fontWeight: '500', color: 'red'},
  textNameModal: {fontSize: 20, fontWeight: '500', color: 'black'},
  textPriceModal: {fontSize: 20, fontWeight: '500', color: 'red'},
  line: {
    height: 2,
    borderWidth: 1,
    marginTop: 10,
    marginHorizontal: 20,
    borderColor: '#fc5653',
  },
  containerDescription: {marginHorizontal: 20, marginTop: 10},
  textLabel: {fontSize: 16, fontWeight: '500', color: 'red'},
  textDescription: {
    fontSize: 14,
    fontWeight: '500',
    color: 'black',
    marginTop: 5,
  },
  containerImageOther: {
    marginTop: 10,
    width: '100%',
    paddingHorizontal: 20,
  },
  innerContainerImageOther: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  viewImageOther: {
    width: '48%',
    height: 150,
    backgroundColor: 'white',
    marginTop: 10,
  },
  imageOther: {width: '100%', height: '100%', borderRadius: 10},
  containerAddToCart: {
    paddingHorizontal: 20,
    marginVertical: 10,
    width: '100%',
    height: 50,
  },
  btnAddToCart: {
    backgroundColor: 'green',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  textBtnAddToCart: {fontSize: 26, color: 'white', fontWeight: '500'},
  containerUpDownQuality: {flexDirection: 'row', gap: 10},
  btnUpDownQuality: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
  },
  textUpAndDownQuality: {fontSize: 18, color: 'black', fontWeight: '500'},
  containerInforModal: {
    height: '65%',
    width: '65%',
    paddingLeft: 10,
    rowGap: 10,
  },
  containerModal: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  containerCardAddToCart: {
    width: '100%',
    height: '30%',
    backgroundColor: 'white',
    padding: 20,
  },
  innerContainerCardAddToCart: {flexDirection: 'row'},
  containerImageModal: {width: '35%', height: '100%'},
  imageModal: {flex: 1, borderRadius: 10},
  containerButton: {
    flex: 1,
    flexDirection: 'row',
    marginTop: 10,
    justifyContent: 'space-between',
  },
  btnCancelModal: {
    width: '47%',
    backgroundColor: '#bdbdbd',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  btnAddToCartModal: {
    width: '47%',
    backgroundColor: 'green',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  textButton: {fontSize: 16, fontWeight: '500', color: 'white'},
});
